# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                remember_me: true
            remember_me:
                    secret:      "%secret%"
                    lifetime: 31536000 # 365 days in seconds
                    path:     /

            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/testcases/guestview/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/testcases, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/testresults/guestview/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/testresults, role: IS_AUTHENTICATED_REMEMBERED }
