services:
    repo.testcase:
        class: AppBundle\Repository\TestcaseRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - "AppBundle:Testcase"
    repo.testresult:
        class: AppBundle\Repository\TestresultRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - "AppBundle:Testresult"
