env:
  global:
  - secure: "r91ryXNl7XZHpVopc759WxVs+PWvpwSLomT+DMVeq8lWN/6jX+cKORa9bbQbaG0zFuFT3/vpebeh9m8/VJSSLTGnRm9hhxS4KL8RsABADd9VoWtV4jJWKQ2CmvTtUnIA3SbkpTziIODUYxckmOj70fvjxqBSF5/Y2KmF3plGgDIlGJpYKWJ8BR5jm+cthWfWH8GWCQgs0uQbYVbF3bNrWR+YCLcL/6DYyQWLmi1gh8SmXkI4TEpI4ihKvxIveqUGoJBGnODPTN9gjmjUdw0MYoFVIwDRwbNtQ8b1tAvNsQemJ1ojpU7+oVSOlZcsWmyjHUGOCIXl20306e7THJSwb0WqfD/aLmI78pM6OUNl7tXBGtpuMG2LtYLBnK/L8Gi2rImmFv0dr/65Ymf2baXCZuTV0fGuJlbJReF2TVGq8WlWKpKCM+wVKRtOH8njg5BHeE5yN676HWDLrVg7IyE/vLMfuDh4EyJsSA4cXYbPifb51U7ERm9qKJRTFcdI3NVokmKz3f5/xltaBWFF2YRg8zXAp/dxc+Mfeu2G8sGr9OHgW6tn9+XuCdwpOKWWvMbuIMqvLgNFZ75XklT7wco/X7v6zv8MTP7PlWPMgwH7Ka6TKbUGJTp1RaZmLG4+gIJaTQShddPWTDkuRTf0IpI8qaIhwoOdLehr7rg6MUQwCUI="
language: php
php:
- 5.5
sudo: required
dist: trusty
branches:
  only:
  - master
  - develop
before_script:
- make travisci-before-script
script:
- make travisci-script
after_success:
- make travisci-after-success
