selenior_api:
    resource: "@SeleniorApiBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

selenior_app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"