api_retrieve_testcases:
    path:     /api/control/testcases
    defaults: { _controller: AppBundle:TestcasesApi:index }
    methods:  [GET]

disable_testcase:
    path:     /testcases/disable/{testcaseId}
    defaults: { _controller: AppBundle:Testcases:disable }
    methods:  [GET]

enable_testcase:
    path:     /testcases/enable/{testcaseId}
    defaults: { _controller: AppBundle:Testcases:enable }
    methods:  [GET]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

selenior_app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"