homepage:
    path:     /
    defaults: { _controller: AppBundle:Testcases:newWithReg }
    methods:  [GET, POST]

imprint:
    path:     /imprint
    defaults: { _controller: AppBundle:Content:imprint }
    methods:  [GET]

testcases.index:
    path:     /testcases/
    defaults: { _controller: AppBundle:Testcases:index }
    methods:  [GET, POST]

testcases.demo.index:
    path:     /demo/testcases/
    defaults: { _controller: AppBundle:Testcases:index }
    methods:  [GET, POST]

testcases.new:
    path:     /testcases/new
    defaults: { _controller: AppBundle:Testcases:new }
    methods:  [GET, POST]

testcases.edit:
    path:     /testcases/{testcaseId}
    defaults: { _controller: AppBundle:Testcases:edit }
    methods:  [GET, POST]

testcases.disable:
    path:     /testcases/{testcaseId}/disable
    defaults: { _controller: AppBundle:Testcases:disable }
    methods:  [POST]

testcases.enable:
    path:     /testcases/{testcaseId}/enable
    defaults: { _controller: AppBundle:Testcases:enable }
    methods:  [POST]

testresults.show:
    path:     /testresults/{testresultId}
    defaults: { _controller: AppBundle:Testresults:show }
    methods:  [GET]

testresults.demo.show:
    path:     /demo/testresults/{testresultId}
    defaults: { _controller: AppBundle:Testresults:show }
    methods:  [GET]

testresult-screenshots:
    path:     /testresult-screenshots/{filename}
    methods:  [GET]

testresult-show-har:
    path:   /api/testresults/{testresultId}/har.jsonp
    methods:  [GET]
