homepage:
    path:     /
    defaults: { _controller: AppBundle:Testcases:newWithReg }
    methods:  [GET, POST]

testcases.new:
    path:     /testcases/new
    defaults: { _controller: AppBundle:Testcases:new }
    methods:  [GET, POST]

api_retrieve_testcases:
    path:     /api/control/testcases
    defaults: { _controller: AppBundle:TestcasesApi:index }
    methods:  [GET]

disable_testcase:
    path:     /testcases/{testcaseId}/disable
    defaults: { _controller: AppBundle:Testcases:disable }
    methods:  [GET]

enable_testcase:
    path:     /testcases/{testcaseId}/enable
    defaults: { _controller: AppBundle:Testcases:enable }
    methods:  [GET]
