homepage:
    path:     /
    defaults: { _controller: AppBundle:Testcases:newWithReg }
    methods:  [GET, POST]

testcases.index:
    path:     /testcases/
    defaults: { _controller: AppBundle:Testcases:index }
    methods:  [GET, POST]

testcases.new:
    path:     /testcases/new
    defaults: { _controller: AppBundle:Testcases:new }
    methods:  [GET, POST]

testcases.edit:
    path:     /testcases/{testcaseId}/edit
    defaults: { _controller: AppBundle:Testcases:edit }
    methods:  [GET, POST]

testcases.disable:
    path:     /testcases/{testcaseId}/disable
    defaults: { _controller: AppBundle:Testcases:disable }
    methods:  [GET]

testcases.enable:
    path:     /testcases/{testcaseId}/enable
    defaults: { _controller: AppBundle:Testcases:enable }
    methods:  [GET]

api.testcases.index:
    path:     /api/control/testcases
    defaults: { _controller: AppBundle:TestcasesApi:index }
    methods:  [GET]
