imports:
    - { resource: repositories.yml }

services:
    selenior.testcase:
        class: AppBundle\Service\TestcaseService
        arguments:
            - @doctrine.orm.entity_manager

    selenior.registration:
        class: AppBundle\Service\RegistrationService
        arguments:
            - @fos_user.user_manager
            - @fos_user.security.login_manager
            - @security.encoder_factory
            - @session
            - @security.token_storage
            - @event_dispatcher

    selenior.registration_confirmation_listener:
        class: AppBundle\EventListener\RegistrationConfirmationListener
        arguments:
            - @selenior.repo.testcase
            - @security.token_storage
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_subscriber }